from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login),
    path('logout/', views.logout),
    path('ad/', views.ad, name='ad'),
    path('login_view/', views.login_view),
    path('plants/', views.plants, name='plants'),
    path('create_plant/', views.create_plant, name="create_plant"),
    path('create_plant_view/', views.create_plant_view, name="create_plant_view"),
    path('edit_plant/', views.edit_plant, name='edit_plant'),
    path('delete_plant/', views.delete_plant, name='delete_plant'),
    path('update_plant/', views.update_plant, name="update_plant"),
    path('fertilizers/', views.fertilizers, name='fertilizers'),
    path('create_fertilizer/', views.create_fertilizer, name="create_fertilizer"),
    path('create_fertilizer_view/', views.create_fertilizer_view, name="create_fertilizer_view"),
    path('edit_fertilizer/', views.edit_fertilizer, name='edit_fertilizer'),
    path('delete_fertilizer/', views.delete_fertilizer, name='delete_fertilizer'),
    path('update_fertilizer/', views.update_fertilizer, name="update_fertilizer"),
    path('diseases/', views.diseases, name='diseases'),
    path('create_disease/', views.create_disease, name="create_disease"),
    path('create_disease_view/', views.create_disease_view, name="create_disease_view"),
    path('edit_disease/', views.edit_disease, name='edit_disease'),
    path('delete_disease/', views.delete_disease, name='delete_disease'),
    path('update_disease/', views.update_disease, name="update_disease"),
    path('soils/', views.soils, name='soils'),
    path('create_soil/', views.create_soil, name="create_soil"),
    path('create_soil_view/', views.create_soil_view, name="create_soil_view"),
    path('edit_soil/', views.edit_soil, name='edit_soil'),
    path('update_soil/', views.update_soil, name="update_soil"),
    path('delete_soil/', views.delete_soil, name='delete_soil'),
    path('devices/', views.devices, name='devices'),
    path('create_device/', views.create_device, name="create_device"),
    path('create_device_view/', views.create_device_view, name="create_device_view"),
    path('edit_device/', views.edit_device, name='edit_device'),
    path('delete_device/', views.delete_device, name='delete_device'),
    path('update_device/', views.update_device, name="update_device"),
]